ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'STUDENT_ID_COPY';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PROOF_OF_FUNDING';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PARENT_ID_COPY';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'ACADEMIC_RECORD';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'ACCEPTANCE_LETTER';
